server:
  port: 10008
spring:
  profiles:
    active: dev
    #active: test # 表示测试环境
    #active: prod


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl