server:
  port: 6666
spring:
  application:
    name: nook-material

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1


feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

